// Vietnamese for the studio's fixed notification phrases. notify() translates through
// this map when the studio is in Vietnamese; messages with names or numbers in them
// are translated where they are written.
export const PHRASES_VI = {
  "AI Director planned the continuation and started generation.": "AI đạo diễn đã lên kịch bản tiếp theo và bắt đầu dựng.",
  "AI idea improvement": "AI hoàn thiện ý tưởng",
  "AI revision failed": "AI chưa sửa được",
  "AI updated the shot prompt.": "AI đã cập nhật mô tả cảnh.",
  "AI updated the storyboard scenes.": "AI đã cập nhật các cảnh trong kịch bản.",
  "All scenes are ready. Adding transitions and the soundtrack…": "Các cảnh đã dựng xong. Đang thêm chuyển cảnh và nhạc nền…",
  "Analyzing product & ingredients to craft cinematic video concept...": "Đang phân tích sản phẩm và tư liệu để viết ý tưởng video…",
  "Asset archived": "Đã xoá tư liệu",
  "Audio added": "Đã thêm âm thanh",
  "Could not reach Qwen planner.": "Không kết nối được AI đạo diễn.",
  "Could not revise shot.": "Chưa sửa được cảnh.",
  "Could not save": "Không thể lưu",
  "Creating storyboard and rendering scenes...": "Đang viết kịch bản và dựng các cảnh…",
  "Error": "Lỗi",
  "Export failed.": "Xuất video thất bại.",
  "Failed to add reference.": "Không thêm được tư liệu tham chiếu.",
  "Failed to archive asset.": "Không xoá được tư liệu.",
  "Failed to create project.": "Không tạo được dự án.",
  "Failed to load project workspace": "Không tải được dự án",
  "Failed to remove reference.": "Không gỡ được tư liệu tham chiếu.",
  "Failed to rename project.": "Không đổi được tên dự án.",
  "Failed to revise storyboard.": "Không sửa được kịch bản.",
  "Failed to save scene.": "Không lưu được cảnh.",
  "Failed to save settings.": "Không lưu được cài đặt.",
  "Failed to set keyframe.": "Không đặt được khung hình chính.",
  "Failed to update duration.": "Không đổi được độ dài.",
  "Failed to update role.": "Không đổi được vai trò.",
  "Failed to upload file.": "Không tải lên được tệp.",
  "Generating your continuation.": "Đang dựng phần tiếp theo.",
  "Generation complete": "Đã dựng xong",
  "Generation error": "Lỗi dựng video",
  "Generation started": "Bắt đầu dựng video",
  "Generation stopped": "Đã dừng dựng video",
  "Generation sync": "Mất kết nối",
  "Idea elevated ✨": "Đã hoàn thiện ý tưởng ✨",
  "Keyframe set": "Đã đặt khung hình chính",
  "Media updated": "Đã lưu tư liệu",
  "Please try again.": "Vui lòng thử lại.",
  "Project name updated.": "Đã đổi tên dự án.",
  "Qwen AI Creative Planner": "AI đạo diễn",
  "Qwen enhanced your concept with cinematic directions and ingredient references.": "AI đã hoàn thiện ý tưởng với hướng quay và tư liệu tham chiếu.",
  "Redo failed": "Không làm lại được",
  "Reference added": "Đã thêm tư liệu tham chiếu",
  "Reference removed from project.": "Đã gỡ tư liệu khỏi dự án.",
  "Removed": "Đã gỡ",
  "Retry failed": "Thử lại thất bại",
  "Retrying": "Đang thử lại",
  "Retrying generation for failed scenes.": "Đang dựng lại các cảnh bị lỗi.",
  "Role updated": "Đã đổi vai trò",
  "Saved": "Đã lưu",
  "Scenes queued": "Đã xếp lịch dựng cảnh",
  "Shot revised": "Đã sửa cảnh",
  "Storyboard": "Kịch bản",
  "Storyboard revised": "Đã sửa kịch bản",
  "The video generation was stopped.": "Đã dừng dựng video.",
  "Timeline edit failed": "Không sửa được dòng thời gian",
  "Timeline export failed": "Xuất video thất bại",
  "Unable to remove scene": "Không xoá được cảnh",
  "Unable to remove scene.": "Không xoá được cảnh.",
  "Unable to stop generation": "Không dừng được việc dựng video",
  "Undo failed": "Không hoàn tác được",
  "Updated": "Đã cập nhật",
  "Upload error": "Lỗi tải lên",
  "Uploaded": "Đã tải lên",
  "Video settings saved.": "Đã lưu cài đặt video.",
  "Connection lost while checking generation. Generation may still be running.": "Mất kết nối khi kiểm tra tiến trình. Video có thể vẫn đang được dựng.",
  "Something went wrong.": "Đã có lỗi xảy ra.",
};
